name: Generate Diagrams

on:
  push:
    branches:
      - diagram_schema
  pull_request:
    branches:
      - diagram_schema

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: sudo apt-get install -y graphviz

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install diagrams graphviz typed-ast

    - name: Generate diagrams
      run: |
        for file in diagram/diagrams/*.py; do
          python3 "$file"
        done

    - name: Upload diagrams
      uses: actions/upload-artifact@v2
      with:
        name: diagrams
        path: output/